artifacts, take 3

diff --git a/.github/workflows/version-release.yml b/.github/workflows/version-release.yml
--- a/.github/workflows/version-release.yml
+++ b/.github/workflows/version-release.yml
@@ -32,6 +32,17 @@ jobs:
       #       echo "INSTALL_EXISTS=false" >> $GITHUB_ENV
       #     fi
 
+      - name: Create .tar.gz artifact
+        run: |
+          tar -czf v${{ steps.read_version.outputs.VERSION }}.tar.gz .
+
+      - name: Verify install file exists
+        run: |
+          if [ ! -f "install" ]; then
+            echo "Error: 'install' file is missing."
+            exit 1
+          fi
+
       - name: Create GitHub Release
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -41,4 +52,6 @@ jobs:
           commit: main
           tag: v${{ steps.read_version.outputs.VERSION }}
           prerelease: ${{ steps.read_version.outputs.PRERELEASE }}
-          artifacts: "install,v${{ steps.read_version.outputs.VERSION }}.tar.gz"
+          artifacts: |
+            install
+            v${{ steps.read_version.outputs.VERSION }}.tar.gz
